/**
 * parseInfobox.js
 * Generated by Claude
 * Parses a MediaWiki "Infobox" template from raw wikitext into a
 * plain JS object of { paramName: rawValue }.
 *
 * Handles the tricky part of infobox wikitext: values often contain
 * nested templates ({{efn|...}}, {{cite web|...}}), wiki links
 * ([[Page|Display]]), and <ref> tags — all of which contain "|" and
 * "=" characters that are NOT infobox field separators. A naive
 * split('|') or split('=') will break on real infoboxes.
 */

/**
 * Extracts the {{Infobox ...}} block from wikitext by matching
 * balanced {{ }} braces (regex alone can't do this because of nesting).
 */
function extractInfoboxBlock(wikitext, infoboxName = 'Infobox') {
  const startMarker = /{{Infobox/i;
  const startMatch = startMarker.exec(wikitext);
  if (!startMatch) return null;

  const start = startMatch.index;
  let depth = 0;
  let i = start;

  for (; i < wikitext.length; i++) {
    if (wikitext.startsWith('{{', i)) {
      depth++;
      i++; // skip second brace
    } else if (wikitext.startsWith('}}', i)) {
      depth--;
      i++; // skip second brace
      if (depth === 0) {
        return wikitext.slice(start, i + 1);
      }
    }
  }
  return null; // unbalanced braces
}

/**
 * Splits the *inside* of a template block into top-level fields,
 * respecting nested {{ }}, [[ ]], and <ref>...</ref> so their
 * internal "|" characters don't cause a false split.
 */
function splitTopLevelFields(inner) {
  const fields = [];
  let depthCurly = 0;
  let depthSquare = 0;
  let inRef = false;
  let current = '';

  for (let i = 0; i < inner.length; i++) {
    const two = inner.slice(i, i + 2);

    if (inner.startsWith('<ref', i)) {
      // Could be a self-closing <ref .../> tag, which needs no matching
      // </ref>. Peek ahead to the end of this opening tag to check.
      const tagEnd = inner.indexOf('>', i);
      const isSelfClosing = tagEnd !== -1 && inner[tagEnd - 1] === '/';
      if (!isSelfClosing) inRef = true;
    }
    if (inner.startsWith('</ref>', i)) inRef = false;

    if (two === '{{') { depthCurly++; current += two; i++; continue; }
    if (two === '}}') { depthCurly--; current += two; i++; continue; }
    if (two === '[[') { depthSquare++; current += two; i++; continue; }
    if (two === ']]') { depthSquare--; current += two; i++; continue; }

    const atTopLevel = depthCurly === 0 && depthSquare === 0 && !inRef;

    if (inner[i] === '|' && atTopLevel) {
      fields.push(current);
      current = '';
    } else {
      current += inner[i];
    }
  }
  if (current.trim()) fields.push(current);
  return fields;
}

/**
 * Strips common wiki markup from a field value so you get readable text.
 * Adjust/extend this depending on how clean you need the output.
 */
// Templates whose arguments are really a list of items (not metadata).
// {{unbulleted list|a|b|c}} etc. should become "a, b, c", not disappear.
const LIST_TEMPLATES = new Set([
  'unbulleted list', 'unbulleted', 'ubl', 'plainlist', 'hlist', 'flatlist', 'br separated entries',
]);

// Templates where you want to keep just the last (displayed) argument.
const PASSTHROUGH_TEMPLATES = new Set([
  'nowrap', 'lang', 'transliteration', 'nativename', 'native name',
  'native phrase', 'langx', 'lang-x', 'center', 'ni', 'small', 'flag', 'nobold',
]);

// A template arg like "link=on" or "item1_style=margin:0" is a named/style
// parameter, not actual content - strip these out before treating the
// remaining positional args as the real list items or display text.
function isNamedParam(arg) {
  return /^\s*[\w-]+\s*=/.test(arg);
}

/**
 * MediaWiki parser functions written with colon syntax rather than pipe
 * syntax, e.g. {{formatnum:41417056}} instead of {{template|arg}}. Each
 * function here takes the raw text after the colon and returns display text.
 */
const COLON_FUNCTIONS = {
  formatnum: (arg) => {
    // Insert thousands separators, preserving a decimal part if present.
    const [intPart, decPart] = arg.split('.');
    const withCommas = intPart.replace(/\B(?=(\d{3})+(?!\d))/g, ',');
    return decPart !== undefined ? `${withCommas}.${decPart}` : withCommas;
  },
  lc: (arg) => arg.toLowerCase(),
  uc: (arg) => arg.toUpperCase(),
  lcfirst: (arg) => arg.charAt(0).toLowerCase() + arg.slice(1),
  ucfirst: (arg) => arg.charAt(0).toUpperCase() + arg.slice(1),
};

/**
 * Finds top-level {{...}} templates in text (brace-depth aware, so it
 * correctly handles templates nested inside other templates) and replaces
 * each one according to its kind: list templates become a joined string
 * of their items, passthrough templates keep their last argument, colon
 * parser functions apply their transform, and everything else (citations,
 * {{efn}}, {{increase}}, icon templates like {{DecreaseNeutral}}, etc.)
 * is dropped.
 */
function processTemplates(text) {
  let out = '';
  let i = 0;

  while (i < text.length) {
    if (text.startsWith('{{', i)) {
      let depth = 0;
      let j = i;
      for (; j < text.length; j++) {
        if (text.startsWith('{{', j)) { depth++; j++; }
        else if (text.startsWith('}}', j)) { depth--; j++; if (depth === 0) { j++; break; } }
      }
      const fullTemplate = text.slice(i, j); // includes outer {{ }}
      const inner = fullTemplate.slice(2, -2);
      const args = splitTopLevelFields(inner); // reuse the same splitter
      const nameRaw = (args[0] || '').trim();
      const name = nameRaw.toLowerCase();
      const rest = args.slice(1);

      // Colon-syntax parser function, e.g. {{formatnum:41417056}} - only
      // when there's no pipe-separated args, since {{cite web|url=...}}
      // style templates never use a colon in the name itself.
      const colonIndex = rest.length === 0 ? name.indexOf(':') : -1;

      if (colonIndex !== -1) {
        const fnName = name.slice(0, colonIndex).trim();
        const fnArg = nameRaw.slice(colonIndex + 1).trim();
        const fn = COLON_FUNCTIONS[fnName];
        out += processTemplates(fn ? fn(fnArg) : fnArg);
      } else if (LIST_TEMPLATES.has(name)) {
        // Drop named/style params like "item1_style=..." and keep real items
        const items = rest
          .filter(a => !isNamedParam(a))
          .map(a => processTemplates(a).trim())
          .filter(Boolean);
        out += items.join(', ');
      } else if (PASSTHROUGH_TEMPLATES.has(name)) {
        // Drop named params like "link=on"/"link=off" before taking the
        // last remaining positional arg (the actual display text).
        const positional = rest.filter(a => !isNamedParam(a));
        if (positional.length) out += processTemplates(positional[positional.length - 1]);
      }
      // else: drop the template entirely (citations, {{efn}}, {{increase}},
      // {{DecreaseNeutral}}/{{IncreaseNeutral}} trend icons, etc.)

      i = j;
    } else {
      out += text[i];
      i++;
    }
  }
  return out;
}


/**
 * Splits raw wikitext on <br/> tags that sit at the TOP LEVEL only -
 * i.e. not nested inside {{templates}}, [[links]], or <ref>...</ref>.
 * This is what lets fields like:
 *   native_name = {{nativename|ar|X}}<br />{{transliteration|ar|Y}}
 *   anthem      = {{native phrase|sv|[[X]]}}<br />({{Langx|en|Y}})<br />[[File:...]]
 * split cleanly into ["X", "Y"], while a <br/> that's nested inside a
 * template's own argument (e.g. a joined {{unbulleted list}} item like
 * "Administrative<br />center") is left alone and stays one string.
 */
function splitTopLevelBr(text) {
  const parts = [];
  let depthCurly = 0;
  let depthSquare = 0;
  let inRef = false;
  let current = '';

  for (let i = 0; i < text.length; i++) {
    if (text.startsWith('<ref', i)) {
      const tagEnd = text.indexOf('>', i);
      const isSelfClosing = tagEnd !== -1 && text[tagEnd - 1] === '/';
      if (!isSelfClosing) inRef = true;
    }
    if (text.startsWith('</ref>', i)) inRef = false;

    const two = text.slice(i, i + 2);
    if (two === '{{') { depthCurly++; current += two; i++; continue; }
    if (two === '}}') { depthCurly--; current += two; i++; continue; }
    if (two === '[[') { depthSquare++; current += two; i++; continue; }
    if (two === ']]') { depthSquare--; current += two; i++; continue; }

    const atTopLevel = depthCurly === 0 && depthSquare === 0 && !inRef;
    const brMatch = atTopLevel && /^<br\s*\/?>/i.exec(text.slice(i, i + 10));

    if (brMatch) {
      parts.push(current);
      current = '';
      i += brMatch[0].length - 1; // -1 since the loop's i++ covers one char
    } else {
      current += text[i];
    }
  }
  parts.push(current);
  return parts;
}

/**
 * Decodes common HTML entities that show up in wikitext - most often
 * &nbsp; (used to glue a number to its unit, e.g. "81.5&nbsp;billion"),
 * but also numeric entities and a few other named ones.
 */
const HTML_ENTITIES = {
  nbsp: ' ', amp: '&', lt: '<', gt: '>', quot: '"', apos: "'",
  mdash: '—', ndash: '–', hellip: '…', minus: '−',
};

function decodeHtmlEntities(str) {
  return str
    .replace(/&#(\d+);/g, (_, code) => String.fromCharCode(Number(code)))
    .replace(/&#x([0-9a-fA-F]+);/g, (_, code) => String.fromCharCode(parseInt(code, 16)))
    .replace(/&(\w+);/g, (match, name) => (name in HTML_ENTITIES ? HTML_ENTITIES[name] : match));
}

/**
 * Cleans a single (already top-level-<br/>-split) chunk of a field value.
 * This is the same pipeline cleanValue used to run directly on the whole
 * value; now it runs once per top-level part.
 */
function cleanSinglePart(value) {
  let v = value;

  // Remove self-closing <ref .../> FIRST, before the open/close pattern,
  // otherwise the open/close regex's non-greedy match can skip past a
  // self-closing ref looking for a "</ref>" that belongs to a later ref.
  v = v.replace(/<ref[^>]*\/>/gi, '');
  v = v.replace(/<ref[^>]*>[\s\S]*?<\/ref>/gi, '');

  // Remove HTML comments
  v = v.replace(/<!--[\s\S]*?-->/g, '');

  // Resolve templates (lists, passthroughs, or drop) before touching links,
  // since template arguments often contain [[links]] of their own.
  v = processTemplates(v);

  // [[File:...]] / [[Image:...]] are embedded media, not readable text - drop entirely
  v = v.replace(/\[\[(?:File|Image):[^\]]*\]\]/gi, '');

  // [[Page|Display]] -> Display, [[Page]] -> Page
  v = v.replace(/\[\[([^\]|]*)\|([^\]]*)\]\]/g, '$2');
  v = v.replace(/\[\[([^\]]*)\]\]/g, '$1');

  // Strip wiki bold/italic markup: '''''bold italic''''', '''bold''', ''italic''
  v = v.replace(/'''''(.*?)'''''/g, '$1');
  v = v.replace(/'''(.*?)'''/g, '$1');
  v = v.replace(/''(.*?)''/g, '$1');

  // Decode HTML entities (&nbsp; -> regular space, &amp; -> &, etc.) BEFORE
  // the whitespace collapse below, since &nbsp; is literal text - the \s
  // regex used for collapsing doesn't match it until it's decoded.
  v = decodeHtmlEntities(v);

  // Remove any remaining (nested, non-top-level) HTML tags like <br />, <div>, <small>
  v = v.replace(/<[^>]+>/g, ' ');

  // Collapse whitespace
  v = v.replace(/\s+/g, ' ').trim();

  return v;
}

/**
 * Cleans a field value. Values with a single top-level part return a
 * plain string, same as before. Values with multiple top-level parts
 * (separated by a <br/> outside any template/link) return an array of
 * cleaned strings - e.g. native_name -> ["دولة فلسطين", "Dawlat Filasṭīn"].
 */
function cleanValue(value) {
  const topParts = splitTopLevelBr(value);
  const cleanedParts = topParts.map(cleanSinglePart).filter(Boolean);

  if (cleanedParts.length > 1) return cleanedParts;
  return cleanedParts[0] || '';
}

/**
 * Converts a wikitext param name like "population_estimate_year" or
 * "GDP_PPP" into JS-conventional camelCase: "populationEstimateYear",
 * "gdpPpp". Words are split on underscores/spaces; each word is
 * lowercased then re-capitalized (except the first), which is the same
 * approach libraries like lodash's camelCase use - so acronyms such as
 * "GDP" or "HDI" come out as "Gdp"/"Hdi" mid-word rather than staying
 * all-caps, keeping the output predictable.
 */
function toCamelCase(key) {
  return key
    .split(/[_\s]+/)
    .filter(Boolean)
    .map((word, i) => {
      const lower = word.toLowerCase();
      return i === 0 ? lower : lower.charAt(0).toUpperCase() + lower.slice(1);
    })
    .join('');
}

/**
 * Main entry point: parses wikitext and returns { field: cleanedValue }.
 * Pass { raw: true } to get uncleaned values instead.
 * Pass { camelCase: false } to keep the raw wiki param names as keys
 * (e.g. "population_estimate") instead of the default camelCase
 * ("populationEstimate").
 */
function parseInfobox(wikitext, infoboxName = 'Infobox', options = {}) {
  const block = extractInfoboxBlock(wikitext, infoboxName);
  if (!block) return null;

  // Strip the outer {{ and }} and the "Infobox X" header up to the first |
  const inner = block.slice(2, -2);
  const firstPipe = inner.indexOf('|');
  const bodyAfterName = inner.slice(firstPipe + 1);

  const fields = splitTopLevelFields(bodyAfterName);
  const useCamelCase = options.camelCase !== false;

  const result = {};
  const infoboxTypeRegex = /{{Infobox (.*)/;
  const infoboxType = infoboxTypeRegex.exec(wikitext);
  if(infoboxType?.[1]){
    result['infoboxType'] = infoboxType[1]
  }
  const shortDesRegex = /{{Short description\|(.*)/;
  const shortDes = infoboxTypeRegex.exec(wikitext);
  if(shortDes?.[1]){
    result['shortDes'] = shortDes[1]
  }
  
  for (const field of fields) {
    const eqIndex = field.indexOf('=');
    if (eqIndex === -1) continue; // no key=value (shouldn't normally happen)

    const rawKey = field.slice(0, eqIndex).trim();
    const key = useCamelCase ? toCamelCase(rawKey) : rawKey;
    const rawValue = field.slice(eqIndex + 1).trim();

    const value = options.raw ? rawValue : cleanValue(rawValue);
    // Ommit empty values
    if (value){
      result[key] = value
    }
  }

  return result;
}

module.exports = { parseInfobox, extractInfoboxBlock, cleanValue, toCamelCase };

// ---- Example usage ----
if (require.main === module) {
  const fs = require('fs');
  const wikitext = fs.readFileSync(process.argv[2] || './sample.wikitext', 'utf8');

  const infobox = parseInfobox(wikitext, 'Infobox country');

  // Pull out just the fields you care about
  const wanted = ['conventionalLongName', 'capital', 'populationEstimate',
                  'populationEstimateYear', 'areaKm2', 'gdpNominal', 'currency'];

  const subset = {};
  for (const key of wanted) {
    if (infobox && key in infobox) subset[key] = infobox[key];
  }

  console.log(subset);
}